// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: request_master.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Master {

  /// <summary>Holder for reflection information generated from request_master.proto</summary>
  public static partial class RequestMasterReflection {

    #region Descriptor
    /// <summary>File descriptor for request_master.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RequestMasterReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRyZXF1ZXN0X21hc3Rlci5wcm90bxIGbWFzdGVyGg9jbGlwYm9hcmQucHJv",
            "dG8izwMKDU1hc3Rlck1lc3NhZ2USDAoEcm5kQhgBIAEoCRIrCg5tb3VzZV9w",
            "b3NpdGlvbhgLIAEoCzIRLm1hc3Rlci5Nb3VzZU1vdmVIABIkCghrZXlib2Fy",
            "ZBgCIAEoCzIQLm1hc3Rlci5LZXlib2FyZEgAEikKC21vdXNlX2NsaWNrGAMg",
            "ASgLMhIubWFzdGVyLk1vdXNlQ2xpY2tIABIpCgttb3VzZV93aGVlbBgIIAEo",
            "CzISLm1hc3Rlci5Nb3VzZVdoZWVsSAASJgoJY2xpcGJvYXJkGAQgASgLMhEu",
            "Y29tbW9uLkNsaXBib2FyZEgAEi0KDXN0YXJ0X3Nlc3Npb24YBSABKAsyFC5t",
            "YXN0ZXIuU2Vzc2lvbkJlZ2luSAASKQoLZW5kX3Nlc3Npb24YBiABKAsyEi5t",
            "YXN0ZXIuU2Vzc2lvbkVuZEgAEiIKB3JlcXVlc3QYByABKA4yDy5tYXN0ZXIu",
            "UmVxdWVzdEgAEiEKCWhhbmRzaGFrZRgJIAEoCzIMLm1hc3Rlci5FY2hvSAAS",
            "JgoJaGVhcnRiZWF0GAogASgLMhEubWFzdGVyLkhlYXJ0YmVhdEgAEgwKBHJu",
            "ZEUYDCABKAlCCAoGYWN0aW9uIkAKBEVjaG8SJwoGcmVzdWx0GAEgASgOMhcu",
            "bWFzdGVyLkhhbmRzaGFrZVJlc3VsdBIPCgdtZXNzYWdlGAIgASgJIhwKCUhl",
            "YXJ0YmVhdBIPCgdvbmVfd2F5GAEgASgIIisKDFNlc3Npb25CZWdpbhIbChNt",
            "b3VzZV9tb3ZlX3JlbGF0aXZlGAEgASgIIgwKClNlc3Npb25FbmQiOgoIS2V5",
            "Ym9hcmQSCwoDa2V5GAEgASgNEiEKCmV2ZW50X3R5cGUYAiABKA4yDS5tYXN0",
            "ZXIuU3RhdGUiIQoJTW91c2VNb3ZlEgkKAVgYASABKAUSCQoBWRgCIAEoBSJP",
            "CgpNb3VzZUNsaWNrEh4KBmJ1dHRvbhgBIAEoDjIOLm1hc3Rlci5CdXR0b24S",
            "IQoKZXZlbnRfdHlwZRgCIAEoDjINLm1hc3Rlci5TdGF0ZSJJCgpNb3VzZVdo",
            "ZWVsEisKEHNjcm9sbF9kaXJlY3Rpb24YASABKA4yES5tYXN0ZXIuRGlyZWN0",
            "aW9uEg4KBmFtb3VudBgCIAEoBSo7CgdSZXF1ZXN0Eg0KCUlOSVRfSU5GTxAA",
            "EhIKDk1PVVNFX1BPU0lUSU9OEAESDQoJQ0xJUEJPQVJEEAIqQQoPSGFuZHNo",
            "YWtlUmVzdWx0EgsKB1N1Y2Nlc3MQABISCg5TdWNjZXNzV2FybmluZxABEg0K",
            "CVJlamVjdGlvbhACKk4KCURpcmVjdGlvbhINCglTQ1JPTExfVVAQABIPCgtT",
            "Q1JPTExfRE9XThABEg8KC1NDUk9MTF9MRUZUEAISEAoMU0NST0xMX1JJR0hU",
            "EAMqRQoGQnV0dG9uEggKBExFRlQQABIJCgVSSUdIVBABEgoKBk1JRERMRRAC",
            "EgwKCFhCVVRUT04xEAMSDAoIWEJVVFRPTjIQBCoiCgVTdGF0ZRILCgdQUkVT",
            "U0VEEAASDAoIUkVMRUFTRUQQAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Common.ClipboardReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Master.Request), typeof(global::Master.HandshakeResult), typeof(global::Master.Direction), typeof(global::Master.Button), typeof(global::Master.State), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Master.MasterMessage), global::Master.MasterMessage.Parser, new[]{ "RndB", "MousePosition", "Keyboard", "MouseClick", "MouseWheel", "Clipboard", "StartSession", "EndSession", "Request", "Handshake", "Heartbeat", "RndE" }, new[]{ "Action" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Master.Echo), global::Master.Echo.Parser, new[]{ "Result", "Message" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Master.Heartbeat), global::Master.Heartbeat.Parser, new[]{ "OneWay" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Master.SessionBegin), global::Master.SessionBegin.Parser, new[]{ "MouseMoveRelative" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Master.SessionEnd), global::Master.SessionEnd.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Master.Keyboard), global::Master.Keyboard.Parser, new[]{ "Key", "EventType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Master.MouseMove), global::Master.MouseMove.Parser, new[]{ "X", "Y" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Master.MouseClick), global::Master.MouseClick.Parser, new[]{ "Button", "EventType" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Master.MouseWheel), global::Master.MouseWheel.Parser, new[]{ "ScrollDirection", "Amount" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Request {
    [pbr::OriginalName("INIT_INFO")] InitInfo = 0,
    [pbr::OriginalName("MOUSE_POSITION")] MousePosition = 1,
    [pbr::OriginalName("CLIPBOARD")] Clipboard = 2,
  }

  public enum HandshakeResult {
    [pbr::OriginalName("Success")] Success = 0,
    [pbr::OriginalName("SuccessWarning")] SuccessWarning = 1,
    [pbr::OriginalName("Rejection")] Rejection = 2,
  }

  public enum Direction {
    [pbr::OriginalName("SCROLL_UP")] ScrollUp = 0,
    [pbr::OriginalName("SCROLL_DOWN")] ScrollDown = 1,
    [pbr::OriginalName("SCROLL_LEFT")] ScrollLeft = 2,
    [pbr::OriginalName("SCROLL_RIGHT")] ScrollRight = 3,
  }

  public enum Button {
    [pbr::OriginalName("LEFT")] Left = 0,
    [pbr::OriginalName("RIGHT")] Right = 1,
    [pbr::OriginalName("MIDDLE")] Middle = 2,
    [pbr::OriginalName("XBUTTON1")] Xbutton1 = 3,
    [pbr::OriginalName("XBUTTON2")] Xbutton2 = 4,
  }

  public enum State {
    [pbr::OriginalName("PRESSED")] Pressed = 0,
    [pbr::OriginalName("RELEASED")] Released = 1,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MasterMessage : pb::IMessage<MasterMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MasterMessage> _parser = new pb::MessageParser<MasterMessage>(() => new MasterMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MasterMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Master.RequestMasterReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MasterMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MasterMessage(MasterMessage other) : this() {
      rndB_ = other.rndB_;
      rndE_ = other.rndE_;
      switch (other.ActionCase) {
        case ActionOneofCase.MousePosition:
          MousePosition = other.MousePosition.Clone();
          break;
        case ActionOneofCase.Keyboard:
          Keyboard = other.Keyboard.Clone();
          break;
        case ActionOneofCase.MouseClick:
          MouseClick = other.MouseClick.Clone();
          break;
        case ActionOneofCase.MouseWheel:
          MouseWheel = other.MouseWheel.Clone();
          break;
        case ActionOneofCase.Clipboard:
          Clipboard = other.Clipboard.Clone();
          break;
        case ActionOneofCase.StartSession:
          StartSession = other.StartSession.Clone();
          break;
        case ActionOneofCase.EndSession:
          EndSession = other.EndSession.Clone();
          break;
        case ActionOneofCase.Request:
          Request = other.Request;
          break;
        case ActionOneofCase.Handshake:
          Handshake = other.Handshake.Clone();
          break;
        case ActionOneofCase.Heartbeat:
          Heartbeat = other.Heartbeat.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MasterMessage Clone() {
      return new MasterMessage(this);
    }

    /// <summary>Field number for the "rndB" field.</summary>
    public const int RndBFieldNumber = 1;
    private string rndB_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RndB {
      get { return rndB_; }
      set {
        rndB_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mouse_position" field.</summary>
    public const int MousePositionFieldNumber = 11;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Master.MouseMove MousePosition {
      get { return actionCase_ == ActionOneofCase.MousePosition ? (global::Master.MouseMove) action_ : null; }
      set {
        action_ = value;
        actionCase_ = value == null ? ActionOneofCase.None : ActionOneofCase.MousePosition;
      }
    }

    /// <summary>Field number for the "keyboard" field.</summary>
    public const int KeyboardFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Master.Keyboard Keyboard {
      get { return actionCase_ == ActionOneofCase.Keyboard ? (global::Master.Keyboard) action_ : null; }
      set {
        action_ = value;
        actionCase_ = value == null ? ActionOneofCase.None : ActionOneofCase.Keyboard;
      }
    }

    /// <summary>Field number for the "mouse_click" field.</summary>
    public const int MouseClickFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Master.MouseClick MouseClick {
      get { return actionCase_ == ActionOneofCase.MouseClick ? (global::Master.MouseClick) action_ : null; }
      set {
        action_ = value;
        actionCase_ = value == null ? ActionOneofCase.None : ActionOneofCase.MouseClick;
      }
    }

    /// <summary>Field number for the "mouse_wheel" field.</summary>
    public const int MouseWheelFieldNumber = 8;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Master.MouseWheel MouseWheel {
      get { return actionCase_ == ActionOneofCase.MouseWheel ? (global::Master.MouseWheel) action_ : null; }
      set {
        action_ = value;
        actionCase_ = value == null ? ActionOneofCase.None : ActionOneofCase.MouseWheel;
      }
    }

    /// <summary>Field number for the "clipboard" field.</summary>
    public const int ClipboardFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Common.Clipboard Clipboard {
      get { return actionCase_ == ActionOneofCase.Clipboard ? (global::Common.Clipboard) action_ : null; }
      set {
        action_ = value;
        actionCase_ = value == null ? ActionOneofCase.None : ActionOneofCase.Clipboard;
      }
    }

    /// <summary>Field number for the "start_session" field.</summary>
    public const int StartSessionFieldNumber = 5;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Master.SessionBegin StartSession {
      get { return actionCase_ == ActionOneofCase.StartSession ? (global::Master.SessionBegin) action_ : null; }
      set {
        action_ = value;
        actionCase_ = value == null ? ActionOneofCase.None : ActionOneofCase.StartSession;
      }
    }

    /// <summary>Field number for the "end_session" field.</summary>
    public const int EndSessionFieldNumber = 6;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Master.SessionEnd EndSession {
      get { return actionCase_ == ActionOneofCase.EndSession ? (global::Master.SessionEnd) action_ : null; }
      set {
        action_ = value;
        actionCase_ = value == null ? ActionOneofCase.None : ActionOneofCase.EndSession;
      }
    }

    /// <summary>Field number for the "request" field.</summary>
    public const int RequestFieldNumber = 7;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Master.Request Request {
      get { return HasRequest ? (global::Master.Request) action_ : global::Master.Request.InitInfo; }
      set {
        action_ = value;
        actionCase_ = ActionOneofCase.Request;
      }
    }
    /// <summary>Gets whether the "request" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasRequest {
      get { return actionCase_ == ActionOneofCase.Request; }
    }
    /// <summary> Clears the value of the oneof if it's currently set to "request" </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRequest() {
      if (HasRequest) {
        ClearAction();
      }
    }

    /// <summary>Field number for the "handshake" field.</summary>
    public const int HandshakeFieldNumber = 9;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Master.Echo Handshake {
      get { return actionCase_ == ActionOneofCase.Handshake ? (global::Master.Echo) action_ : null; }
      set {
        action_ = value;
        actionCase_ = value == null ? ActionOneofCase.None : ActionOneofCase.Handshake;
      }
    }

    /// <summary>Field number for the "heartbeat" field.</summary>
    public const int HeartbeatFieldNumber = 10;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Master.Heartbeat Heartbeat {
      get { return actionCase_ == ActionOneofCase.Heartbeat ? (global::Master.Heartbeat) action_ : null; }
      set {
        action_ = value;
        actionCase_ = value == null ? ActionOneofCase.None : ActionOneofCase.Heartbeat;
      }
    }

    /// <summary>Field number for the "rndE" field.</summary>
    public const int RndEFieldNumber = 12;
    private string rndE_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string RndE {
      get { return rndE_; }
      set {
        rndE_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    private object action_;
    /// <summary>Enum of possible cases for the "action" oneof.</summary>
    public enum ActionOneofCase {
      None = 0,
      MousePosition = 11,
      Keyboard = 2,
      MouseClick = 3,
      MouseWheel = 8,
      Clipboard = 4,
      StartSession = 5,
      EndSession = 6,
      Request = 7,
      Handshake = 9,
      Heartbeat = 10,
    }
    private ActionOneofCase actionCase_ = ActionOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ActionOneofCase ActionCase {
      get { return actionCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearAction() {
      actionCase_ = ActionOneofCase.None;
      action_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MasterMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MasterMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RndB != other.RndB) return false;
      if (!object.Equals(MousePosition, other.MousePosition)) return false;
      if (!object.Equals(Keyboard, other.Keyboard)) return false;
      if (!object.Equals(MouseClick, other.MouseClick)) return false;
      if (!object.Equals(MouseWheel, other.MouseWheel)) return false;
      if (!object.Equals(Clipboard, other.Clipboard)) return false;
      if (!object.Equals(StartSession, other.StartSession)) return false;
      if (!object.Equals(EndSession, other.EndSession)) return false;
      if (Request != other.Request) return false;
      if (!object.Equals(Handshake, other.Handshake)) return false;
      if (!object.Equals(Heartbeat, other.Heartbeat)) return false;
      if (RndE != other.RndE) return false;
      if (ActionCase != other.ActionCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RndB.Length != 0) hash ^= RndB.GetHashCode();
      if (actionCase_ == ActionOneofCase.MousePosition) hash ^= MousePosition.GetHashCode();
      if (actionCase_ == ActionOneofCase.Keyboard) hash ^= Keyboard.GetHashCode();
      if (actionCase_ == ActionOneofCase.MouseClick) hash ^= MouseClick.GetHashCode();
      if (actionCase_ == ActionOneofCase.MouseWheel) hash ^= MouseWheel.GetHashCode();
      if (actionCase_ == ActionOneofCase.Clipboard) hash ^= Clipboard.GetHashCode();
      if (actionCase_ == ActionOneofCase.StartSession) hash ^= StartSession.GetHashCode();
      if (actionCase_ == ActionOneofCase.EndSession) hash ^= EndSession.GetHashCode();
      if (HasRequest) hash ^= Request.GetHashCode();
      if (actionCase_ == ActionOneofCase.Handshake) hash ^= Handshake.GetHashCode();
      if (actionCase_ == ActionOneofCase.Heartbeat) hash ^= Heartbeat.GetHashCode();
      if (RndE.Length != 0) hash ^= RndE.GetHashCode();
      hash ^= (int) actionCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RndB.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RndB);
      }
      if (actionCase_ == ActionOneofCase.Keyboard) {
        output.WriteRawTag(18);
        output.WriteMessage(Keyboard);
      }
      if (actionCase_ == ActionOneofCase.MouseClick) {
        output.WriteRawTag(26);
        output.WriteMessage(MouseClick);
      }
      if (actionCase_ == ActionOneofCase.Clipboard) {
        output.WriteRawTag(34);
        output.WriteMessage(Clipboard);
      }
      if (actionCase_ == ActionOneofCase.StartSession) {
        output.WriteRawTag(42);
        output.WriteMessage(StartSession);
      }
      if (actionCase_ == ActionOneofCase.EndSession) {
        output.WriteRawTag(50);
        output.WriteMessage(EndSession);
      }
      if (HasRequest) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Request);
      }
      if (actionCase_ == ActionOneofCase.MouseWheel) {
        output.WriteRawTag(66);
        output.WriteMessage(MouseWheel);
      }
      if (actionCase_ == ActionOneofCase.Handshake) {
        output.WriteRawTag(74);
        output.WriteMessage(Handshake);
      }
      if (actionCase_ == ActionOneofCase.Heartbeat) {
        output.WriteRawTag(82);
        output.WriteMessage(Heartbeat);
      }
      if (actionCase_ == ActionOneofCase.MousePosition) {
        output.WriteRawTag(90);
        output.WriteMessage(MousePosition);
      }
      if (RndE.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(RndE);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RndB.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(RndB);
      }
      if (actionCase_ == ActionOneofCase.Keyboard) {
        output.WriteRawTag(18);
        output.WriteMessage(Keyboard);
      }
      if (actionCase_ == ActionOneofCase.MouseClick) {
        output.WriteRawTag(26);
        output.WriteMessage(MouseClick);
      }
      if (actionCase_ == ActionOneofCase.Clipboard) {
        output.WriteRawTag(34);
        output.WriteMessage(Clipboard);
      }
      if (actionCase_ == ActionOneofCase.StartSession) {
        output.WriteRawTag(42);
        output.WriteMessage(StartSession);
      }
      if (actionCase_ == ActionOneofCase.EndSession) {
        output.WriteRawTag(50);
        output.WriteMessage(EndSession);
      }
      if (HasRequest) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Request);
      }
      if (actionCase_ == ActionOneofCase.MouseWheel) {
        output.WriteRawTag(66);
        output.WriteMessage(MouseWheel);
      }
      if (actionCase_ == ActionOneofCase.Handshake) {
        output.WriteRawTag(74);
        output.WriteMessage(Handshake);
      }
      if (actionCase_ == ActionOneofCase.Heartbeat) {
        output.WriteRawTag(82);
        output.WriteMessage(Heartbeat);
      }
      if (actionCase_ == ActionOneofCase.MousePosition) {
        output.WriteRawTag(90);
        output.WriteMessage(MousePosition);
      }
      if (RndE.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(RndE);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RndB.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RndB);
      }
      if (actionCase_ == ActionOneofCase.MousePosition) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MousePosition);
      }
      if (actionCase_ == ActionOneofCase.Keyboard) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Keyboard);
      }
      if (actionCase_ == ActionOneofCase.MouseClick) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MouseClick);
      }
      if (actionCase_ == ActionOneofCase.MouseWheel) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MouseWheel);
      }
      if (actionCase_ == ActionOneofCase.Clipboard) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Clipboard);
      }
      if (actionCase_ == ActionOneofCase.StartSession) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StartSession);
      }
      if (actionCase_ == ActionOneofCase.EndSession) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EndSession);
      }
      if (HasRequest) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Request);
      }
      if (actionCase_ == ActionOneofCase.Handshake) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Handshake);
      }
      if (actionCase_ == ActionOneofCase.Heartbeat) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Heartbeat);
      }
      if (RndE.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(RndE);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MasterMessage other) {
      if (other == null) {
        return;
      }
      if (other.RndB.Length != 0) {
        RndB = other.RndB;
      }
      if (other.RndE.Length != 0) {
        RndE = other.RndE;
      }
      switch (other.ActionCase) {
        case ActionOneofCase.MousePosition:
          if (MousePosition == null) {
            MousePosition = new global::Master.MouseMove();
          }
          MousePosition.MergeFrom(other.MousePosition);
          break;
        case ActionOneofCase.Keyboard:
          if (Keyboard == null) {
            Keyboard = new global::Master.Keyboard();
          }
          Keyboard.MergeFrom(other.Keyboard);
          break;
        case ActionOneofCase.MouseClick:
          if (MouseClick == null) {
            MouseClick = new global::Master.MouseClick();
          }
          MouseClick.MergeFrom(other.MouseClick);
          break;
        case ActionOneofCase.MouseWheel:
          if (MouseWheel == null) {
            MouseWheel = new global::Master.MouseWheel();
          }
          MouseWheel.MergeFrom(other.MouseWheel);
          break;
        case ActionOneofCase.Clipboard:
          if (Clipboard == null) {
            Clipboard = new global::Common.Clipboard();
          }
          Clipboard.MergeFrom(other.Clipboard);
          break;
        case ActionOneofCase.StartSession:
          if (StartSession == null) {
            StartSession = new global::Master.SessionBegin();
          }
          StartSession.MergeFrom(other.StartSession);
          break;
        case ActionOneofCase.EndSession:
          if (EndSession == null) {
            EndSession = new global::Master.SessionEnd();
          }
          EndSession.MergeFrom(other.EndSession);
          break;
        case ActionOneofCase.Request:
          Request = other.Request;
          break;
        case ActionOneofCase.Handshake:
          if (Handshake == null) {
            Handshake = new global::Master.Echo();
          }
          Handshake.MergeFrom(other.Handshake);
          break;
        case ActionOneofCase.Heartbeat:
          if (Heartbeat == null) {
            Heartbeat = new global::Master.Heartbeat();
          }
          Heartbeat.MergeFrom(other.Heartbeat);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            RndB = input.ReadString();
            break;
          }
          case 18: {
            global::Master.Keyboard subBuilder = new global::Master.Keyboard();
            if (actionCase_ == ActionOneofCase.Keyboard) {
              subBuilder.MergeFrom(Keyboard);
            }
            input.ReadMessage(subBuilder);
            Keyboard = subBuilder;
            break;
          }
          case 26: {
            global::Master.MouseClick subBuilder = new global::Master.MouseClick();
            if (actionCase_ == ActionOneofCase.MouseClick) {
              subBuilder.MergeFrom(MouseClick);
            }
            input.ReadMessage(subBuilder);
            MouseClick = subBuilder;
            break;
          }
          case 34: {
            global::Common.Clipboard subBuilder = new global::Common.Clipboard();
            if (actionCase_ == ActionOneofCase.Clipboard) {
              subBuilder.MergeFrom(Clipboard);
            }
            input.ReadMessage(subBuilder);
            Clipboard = subBuilder;
            break;
          }
          case 42: {
            global::Master.SessionBegin subBuilder = new global::Master.SessionBegin();
            if (actionCase_ == ActionOneofCase.StartSession) {
              subBuilder.MergeFrom(StartSession);
            }
            input.ReadMessage(subBuilder);
            StartSession = subBuilder;
            break;
          }
          case 50: {
            global::Master.SessionEnd subBuilder = new global::Master.SessionEnd();
            if (actionCase_ == ActionOneofCase.EndSession) {
              subBuilder.MergeFrom(EndSession);
            }
            input.ReadMessage(subBuilder);
            EndSession = subBuilder;
            break;
          }
          case 56: {
            action_ = input.ReadEnum();
            actionCase_ = ActionOneofCase.Request;
            break;
          }
          case 66: {
            global::Master.MouseWheel subBuilder = new global::Master.MouseWheel();
            if (actionCase_ == ActionOneofCase.MouseWheel) {
              subBuilder.MergeFrom(MouseWheel);
            }
            input.ReadMessage(subBuilder);
            MouseWheel = subBuilder;
            break;
          }
          case 74: {
            global::Master.Echo subBuilder = new global::Master.Echo();
            if (actionCase_ == ActionOneofCase.Handshake) {
              subBuilder.MergeFrom(Handshake);
            }
            input.ReadMessage(subBuilder);
            Handshake = subBuilder;
            break;
          }
          case 82: {
            global::Master.Heartbeat subBuilder = new global::Master.Heartbeat();
            if (actionCase_ == ActionOneofCase.Heartbeat) {
              subBuilder.MergeFrom(Heartbeat);
            }
            input.ReadMessage(subBuilder);
            Heartbeat = subBuilder;
            break;
          }
          case 90: {
            global::Master.MouseMove subBuilder = new global::Master.MouseMove();
            if (actionCase_ == ActionOneofCase.MousePosition) {
              subBuilder.MergeFrom(MousePosition);
            }
            input.ReadMessage(subBuilder);
            MousePosition = subBuilder;
            break;
          }
          case 98: {
            RndE = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            RndB = input.ReadString();
            break;
          }
          case 18: {
            global::Master.Keyboard subBuilder = new global::Master.Keyboard();
            if (actionCase_ == ActionOneofCase.Keyboard) {
              subBuilder.MergeFrom(Keyboard);
            }
            input.ReadMessage(subBuilder);
            Keyboard = subBuilder;
            break;
          }
          case 26: {
            global::Master.MouseClick subBuilder = new global::Master.MouseClick();
            if (actionCase_ == ActionOneofCase.MouseClick) {
              subBuilder.MergeFrom(MouseClick);
            }
            input.ReadMessage(subBuilder);
            MouseClick = subBuilder;
            break;
          }
          case 34: {
            global::Common.Clipboard subBuilder = new global::Common.Clipboard();
            if (actionCase_ == ActionOneofCase.Clipboard) {
              subBuilder.MergeFrom(Clipboard);
            }
            input.ReadMessage(subBuilder);
            Clipboard = subBuilder;
            break;
          }
          case 42: {
            global::Master.SessionBegin subBuilder = new global::Master.SessionBegin();
            if (actionCase_ == ActionOneofCase.StartSession) {
              subBuilder.MergeFrom(StartSession);
            }
            input.ReadMessage(subBuilder);
            StartSession = subBuilder;
            break;
          }
          case 50: {
            global::Master.SessionEnd subBuilder = new global::Master.SessionEnd();
            if (actionCase_ == ActionOneofCase.EndSession) {
              subBuilder.MergeFrom(EndSession);
            }
            input.ReadMessage(subBuilder);
            EndSession = subBuilder;
            break;
          }
          case 56: {
            action_ = input.ReadEnum();
            actionCase_ = ActionOneofCase.Request;
            break;
          }
          case 66: {
            global::Master.MouseWheel subBuilder = new global::Master.MouseWheel();
            if (actionCase_ == ActionOneofCase.MouseWheel) {
              subBuilder.MergeFrom(MouseWheel);
            }
            input.ReadMessage(subBuilder);
            MouseWheel = subBuilder;
            break;
          }
          case 74: {
            global::Master.Echo subBuilder = new global::Master.Echo();
            if (actionCase_ == ActionOneofCase.Handshake) {
              subBuilder.MergeFrom(Handshake);
            }
            input.ReadMessage(subBuilder);
            Handshake = subBuilder;
            break;
          }
          case 82: {
            global::Master.Heartbeat subBuilder = new global::Master.Heartbeat();
            if (actionCase_ == ActionOneofCase.Heartbeat) {
              subBuilder.MergeFrom(Heartbeat);
            }
            input.ReadMessage(subBuilder);
            Heartbeat = subBuilder;
            break;
          }
          case 90: {
            global::Master.MouseMove subBuilder = new global::Master.MouseMove();
            if (actionCase_ == ActionOneofCase.MousePosition) {
              subBuilder.MergeFrom(MousePosition);
            }
            input.ReadMessage(subBuilder);
            MousePosition = subBuilder;
            break;
          }
          case 98: {
            RndE = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Echo : pb::IMessage<Echo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Echo> _parser = new pb::MessageParser<Echo>(() => new Echo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Echo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Master.RequestMasterReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Echo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Echo(Echo other) : this() {
      result_ = other.result_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Echo Clone() {
      return new Echo(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::Master.HandshakeResult result_ = global::Master.HandshakeResult.Success;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Master.HandshakeResult Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Echo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Echo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != global::Master.HandshakeResult.Success) hash ^= Result.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Result != global::Master.HandshakeResult.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Result != global::Master.HandshakeResult.Success) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Result != global::Master.HandshakeResult.Success) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Echo other) {
      if (other == null) {
        return;
      }
      if (other.Result != global::Master.HandshakeResult.Success) {
        Result = other.Result;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = (global::Master.HandshakeResult) input.ReadEnum();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = (global::Master.HandshakeResult) input.ReadEnum();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Heartbeat : pb::IMessage<Heartbeat>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Heartbeat> _parser = new pb::MessageParser<Heartbeat>(() => new Heartbeat());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Heartbeat> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Master.RequestMasterReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Heartbeat() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Heartbeat(Heartbeat other) : this() {
      oneWay_ = other.oneWay_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Heartbeat Clone() {
      return new Heartbeat(this);
    }

    /// <summary>Field number for the "one_way" field.</summary>
    public const int OneWayFieldNumber = 1;
    private bool oneWay_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool OneWay {
      get { return oneWay_; }
      set {
        oneWay_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Heartbeat);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Heartbeat other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OneWay != other.OneWay) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (OneWay != false) hash ^= OneWay.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (OneWay != false) {
        output.WriteRawTag(8);
        output.WriteBool(OneWay);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (OneWay != false) {
        output.WriteRawTag(8);
        output.WriteBool(OneWay);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (OneWay != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Heartbeat other) {
      if (other == null) {
        return;
      }
      if (other.OneWay != false) {
        OneWay = other.OneWay;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OneWay = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            OneWay = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SessionBegin : pb::IMessage<SessionBegin>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SessionBegin> _parser = new pb::MessageParser<SessionBegin>(() => new SessionBegin());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SessionBegin> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Master.RequestMasterReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionBegin() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionBegin(SessionBegin other) : this() {
      mouseMoveRelative_ = other.mouseMoveRelative_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionBegin Clone() {
      return new SessionBegin(this);
    }

    /// <summary>Field number for the "mouse_move_relative" field.</summary>
    public const int MouseMoveRelativeFieldNumber = 1;
    private bool mouseMoveRelative_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool MouseMoveRelative {
      get { return mouseMoveRelative_; }
      set {
        mouseMoveRelative_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SessionBegin);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SessionBegin other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MouseMoveRelative != other.MouseMoveRelative) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MouseMoveRelative != false) hash ^= MouseMoveRelative.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MouseMoveRelative != false) {
        output.WriteRawTag(8);
        output.WriteBool(MouseMoveRelative);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MouseMoveRelative != false) {
        output.WriteRawTag(8);
        output.WriteBool(MouseMoveRelative);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MouseMoveRelative != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SessionBegin other) {
      if (other == null) {
        return;
      }
      if (other.MouseMoveRelative != false) {
        MouseMoveRelative = other.MouseMoveRelative;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MouseMoveRelative = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MouseMoveRelative = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SessionEnd : pb::IMessage<SessionEnd>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SessionEnd> _parser = new pb::MessageParser<SessionEnd>(() => new SessionEnd());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SessionEnd> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Master.RequestMasterReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionEnd() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionEnd(SessionEnd other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SessionEnd Clone() {
      return new SessionEnd(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SessionEnd);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SessionEnd other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SessionEnd other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Keyboard : pb::IMessage<Keyboard>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Keyboard> _parser = new pb::MessageParser<Keyboard>(() => new Keyboard());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Keyboard> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Master.RequestMasterReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Keyboard() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Keyboard(Keyboard other) : this() {
      key_ = other.key_;
      eventType_ = other.eventType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Keyboard Clone() {
      return new Keyboard(this);
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 1;
    private uint key_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Key {
      get { return key_; }
      set {
        key_ = value;
      }
    }

    /// <summary>Field number for the "event_type" field.</summary>
    public const int EventTypeFieldNumber = 2;
    private global::Master.State eventType_ = global::Master.State.Pressed;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Master.State EventType {
      get { return eventType_; }
      set {
        eventType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Keyboard);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Keyboard other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Key != other.Key) return false;
      if (EventType != other.EventType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Key != 0) hash ^= Key.GetHashCode();
      if (EventType != global::Master.State.Pressed) hash ^= EventType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Key != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Key);
      }
      if (EventType != global::Master.State.Pressed) {
        output.WriteRawTag(16);
        output.WriteEnum((int) EventType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Key != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Key);
      }
      if (EventType != global::Master.State.Pressed) {
        output.WriteRawTag(16);
        output.WriteEnum((int) EventType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Key != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Key);
      }
      if (EventType != global::Master.State.Pressed) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EventType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Keyboard other) {
      if (other == null) {
        return;
      }
      if (other.Key != 0) {
        Key = other.Key;
      }
      if (other.EventType != global::Master.State.Pressed) {
        EventType = other.EventType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Key = input.ReadUInt32();
            break;
          }
          case 16: {
            EventType = (global::Master.State) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Key = input.ReadUInt32();
            break;
          }
          case 16: {
            EventType = (global::Master.State) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MouseMove : pb::IMessage<MouseMove>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MouseMove> _parser = new pb::MessageParser<MouseMove>(() => new MouseMove());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MouseMove> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Master.RequestMasterReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MouseMove() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MouseMove(MouseMove other) : this() {
      x_ = other.x_;
      y_ = other.y_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MouseMove Clone() {
      return new MouseMove(this);
    }

    /// <summary>Field number for the "X" field.</summary>
    public const int XFieldNumber = 1;
    private int x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "Y" field.</summary>
    public const int YFieldNumber = 2;
    private int y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MouseMove);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MouseMove other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (X != other.X) return false;
      if (Y != other.Y) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (X != 0) hash ^= X.GetHashCode();
      if (Y != 0) hash ^= Y.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (X != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(X);
      }
      if (Y != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Y);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (X != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(X);
      }
      if (Y != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Y);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (X != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(X);
      }
      if (Y != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Y);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MouseMove other) {
      if (other == null) {
        return;
      }
      if (other.X != 0) {
        X = other.X;
      }
      if (other.Y != 0) {
        Y = other.Y;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            X = input.ReadInt32();
            break;
          }
          case 16: {
            Y = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            X = input.ReadInt32();
            break;
          }
          case 16: {
            Y = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MouseClick : pb::IMessage<MouseClick>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MouseClick> _parser = new pb::MessageParser<MouseClick>(() => new MouseClick());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MouseClick> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Master.RequestMasterReflection.Descriptor.MessageTypes[7]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MouseClick() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MouseClick(MouseClick other) : this() {
      button_ = other.button_;
      eventType_ = other.eventType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MouseClick Clone() {
      return new MouseClick(this);
    }

    /// <summary>Field number for the "button" field.</summary>
    public const int ButtonFieldNumber = 1;
    private global::Master.Button button_ = global::Master.Button.Left;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Master.Button Button {
      get { return button_; }
      set {
        button_ = value;
      }
    }

    /// <summary>Field number for the "event_type" field.</summary>
    public const int EventTypeFieldNumber = 2;
    private global::Master.State eventType_ = global::Master.State.Pressed;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Master.State EventType {
      get { return eventType_; }
      set {
        eventType_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MouseClick);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MouseClick other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Button != other.Button) return false;
      if (EventType != other.EventType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Button != global::Master.Button.Left) hash ^= Button.GetHashCode();
      if (EventType != global::Master.State.Pressed) hash ^= EventType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Button != global::Master.Button.Left) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Button);
      }
      if (EventType != global::Master.State.Pressed) {
        output.WriteRawTag(16);
        output.WriteEnum((int) EventType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Button != global::Master.Button.Left) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Button);
      }
      if (EventType != global::Master.State.Pressed) {
        output.WriteRawTag(16);
        output.WriteEnum((int) EventType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Button != global::Master.Button.Left) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Button);
      }
      if (EventType != global::Master.State.Pressed) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EventType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MouseClick other) {
      if (other == null) {
        return;
      }
      if (other.Button != global::Master.Button.Left) {
        Button = other.Button;
      }
      if (other.EventType != global::Master.State.Pressed) {
        EventType = other.EventType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Button = (global::Master.Button) input.ReadEnum();
            break;
          }
          case 16: {
            EventType = (global::Master.State) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Button = (global::Master.Button) input.ReadEnum();
            break;
          }
          case 16: {
            EventType = (global::Master.State) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MouseWheel : pb::IMessage<MouseWheel>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MouseWheel> _parser = new pb::MessageParser<MouseWheel>(() => new MouseWheel());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MouseWheel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Master.RequestMasterReflection.Descriptor.MessageTypes[8]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MouseWheel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MouseWheel(MouseWheel other) : this() {
      scrollDirection_ = other.scrollDirection_;
      amount_ = other.amount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MouseWheel Clone() {
      return new MouseWheel(this);
    }

    /// <summary>Field number for the "scroll_direction" field.</summary>
    public const int ScrollDirectionFieldNumber = 1;
    private global::Master.Direction scrollDirection_ = global::Master.Direction.ScrollUp;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Master.Direction ScrollDirection {
      get { return scrollDirection_; }
      set {
        scrollDirection_ = value;
      }
    }

    /// <summary>Field number for the "amount" field.</summary>
    public const int AmountFieldNumber = 2;
    private int amount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Amount {
      get { return amount_; }
      set {
        amount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MouseWheel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MouseWheel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ScrollDirection != other.ScrollDirection) return false;
      if (Amount != other.Amount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ScrollDirection != global::Master.Direction.ScrollUp) hash ^= ScrollDirection.GetHashCode();
      if (Amount != 0) hash ^= Amount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ScrollDirection != global::Master.Direction.ScrollUp) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ScrollDirection);
      }
      if (Amount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Amount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ScrollDirection != global::Master.Direction.ScrollUp) {
        output.WriteRawTag(8);
        output.WriteEnum((int) ScrollDirection);
      }
      if (Amount != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Amount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ScrollDirection != global::Master.Direction.ScrollUp) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ScrollDirection);
      }
      if (Amount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Amount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MouseWheel other) {
      if (other == null) {
        return;
      }
      if (other.ScrollDirection != global::Master.Direction.ScrollUp) {
        ScrollDirection = other.ScrollDirection;
      }
      if (other.Amount != 0) {
        Amount = other.Amount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ScrollDirection = (global::Master.Direction) input.ReadEnum();
            break;
          }
          case 16: {
            Amount = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ScrollDirection = (global::Master.Direction) input.ReadEnum();
            break;
          }
          case 16: {
            Amount = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
